-- Los datos de referencia (grupos, etapas, selecciones base, bracket) viven en
-- una migración (0009_seed_reference.sql) para que existan también en producción.
-- El fixture/resultados reales se traen con `npm run sync:fixtures`.
-- Para datos de prueba en desarrollo: `npm run seed:demo`.
